title: Áleson Medeiros | Blog
email: contato@pinguimcriativo.com
author: Áleson Santos de Medeiros
description: Meu Blog pessoal.
baseurl: ''
url: 'https://alesonmedeiros.github.io'
date_format: '%b %-d, %Y'
header_pages:
  - index.html
  - about.md
  - contact.html
google_analytics: null
animated: true
show_related_posts: true
show_post_footers: false
show_social_icons: true
post_preview_image: false
disqus_shortname: null
github_username: alesonmedeiros
twitter_username: alesonmedeiros
show_sharing_icons: true
share_twitter: true
text:
  pagination:
    newer: Postagens Novas
    older: Postagens Antigas
  share_buttons:
    text: 'Compartilhe:'
    facebook: Compartilhe no Facebook
    twitter: Compartilhe no Twitter
    googleplus: Compartilhe no Google+
    linkedin: Compartilhe no LinkedIn
    digg: Compartilhe no Digg
    tumblr: Compartilhe no Tumblr
    reddit: Compartilhe no Reddit
    stumbleupon: Compartilhe no StumbleUpon
    hackernews: Compartilhe no Hacker News
  post:
    updated: Updated
    minute_read: Tempo de Leitura
    related_posts: Posts Relacionados
    post_footer: Lorem ipsum
  index:
    coming_soon: Coming soon...
  og_locale: pt_BR
markdown: kramdown
redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data
permalink: ':title'
paginate: 4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
